name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout compat
        uses: actions/checkout@v6
        with:
          repository: SanmerApps/ServiceManagerCompat
          path: compat

      - name: Set up signing key
        if: github.ref == 'refs/heads/main'
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo key.store.password='${{ secrets.KEY_STORE_PASSWORD }}' >> signing.properties
            echo key.alias='${{ secrets.KEY_ALIAS }}' >> signing.properties
            echo key.password='${{ secrets.KEY_PASSWORD }}' >> signing.properties
            echo key.store='${{ github.workspace }}/key.jks' >> signing.properties
            echo ${{ secrets.KEY_STORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: 21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build compat
        working-directory: compat
        run: ./gradlew publishToMavenLocal

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload full apk
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          name: full-apk
          path: app/build/outputs/apk/full/release

      - name: Upload full mapping
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          name: full-mapping
          path: app/build/outputs/mapping/fullRelease

      - name: Upload lite apk
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          name: lite-apk
          path: app/build/outputs/apk/lite/release

      - name: Upload lite mapping
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          name: lite-mapping
          path: app/build/outputs/mapping/liteRelease
